db:
    mode: mysql
    db_name: "testfiber"
    host: 127.0.0.1
    port: 3306
    user: your_username
    password: your_password
redis:
    addr: "127.0.0.1:6379"
    password: "your redis password"
    db: 1
system:
    mode: release
    host: 127.0.0.1
    port: 8000
    env: debug
    version: 1.0.1
    allow_origins:
        - http://localhost:3000
        - http://127.0.0.1:8000
        - http://localhost:6678/
log:
    prefix: "your app name"
    filename: ./logs/blog.log
    max_size: 100    # MB
    max_backups: 7
    max_age: 28
    compress: false
jwt:
    issuer: "xxxx"
    access_secret: "xxxxx"
    refresh_secret: "xxxx"
    access_expire: 2   # hour
    refresh_expire: 168 # hour（7day）
